### PR TITLE
Update requirements.txt

### PR DESCRIPTION
**Pull request by mvcisback**

### CODE REVIEW

**Comment by mvcisback** [comment]
@MarkusRabe 

Hey, there were recently a few bug fixes in py-aiger that seem to be breaking the safety game test. If you have time, do you mind either sending some resources about how the safety game stuff works or checking if the test actually found a bug (either is aiger or aiger-analysis)?

**Comment by MarkusRabe** [comment]
Noticed it as well. Checking it out now.

**Comment by MarkusRabe** [comment]
Suspecting it is a latch initialization bug. Maybe in safety_games.py. Will look into it tonight.

**Comment by MarkusRabe** [comment]
LGTM

**Pull request merged**
